version: 2
jobs:
  build:
    working_directory: /dockerfiles
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup Docker image cache
          command: |
            set +o pipefail
            export CACHE_DIR=/caches
      - run:
          name: Build Docker images
          command: |
            apk add --no-cache make
            make build
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches
