version: "3"
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./data/mysql:/var/lib/mysql
  coordinator:
    build:
      context: .
    restart: always
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8443:8443"
    volumes:
      - ./catalog:/opt/presto/etc/catalog
      - ./config/coordinator/config.properties:/opt/presto/etc/config.properties
  worker:
    build:
      context: .
    restart: always
    volumes:
      - ./catalog:/opt/presto/etc/catalog
      - ./config/worker/config.properties:/opt/presto/etc/config.properties
