version: "3"
services:
  coordinator:
    build:
      context: .
    restart: always
    env_file: .env
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8443:8443"
    volumes:
      - ./../presto/config/coordinator/config.properties:/opt/presto/etc/config.properties
  worker:
    build:
      context: .
    restart: always
    env_file: .env
    volumes:
      - ./../presto/config/worker/config.properties:/opt/presto/etc/config.properties
